<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Unidade extends Model
{
    use HasFactory;

    protected $fillable = [
        "id",
        "nome",
        "nome_fantasia",
        "cnpj",
        "telefone_contato",
        "cep",
        "rua",
        "numero",
        "complemento",
        "bairro",
        "cidade",
        "estado"
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope('created', function ($query) {
            $query->orderBy('created_at', 'desc');
        });

    }

    public function users(): HasMany
    {
        return $this->hasMany(User::class);
    }
}
